[package]
name = "ig"
version = "0.1.0"
authors = ["Konrad Szymoniak <szymoniak.konrad@gmail.com>"]
description = "Interactive Grep"
edition = "2021"

[dependencies]
grep = "0.2.8"
ignore = "0.4.17"
clap = { version = "3.0.14", features = ["derive"] }
crossterm = "0.23.0"
tui = { version = "0.17", default-features = false, features = ['crossterm'] }
unicode-width = "0.1"
itertools = "0.10.0"
anyhow = "1.0.38"
